<a href="https://colab.research.google.com/github/jeffersonramelo/workshop-ufu/blob/main/Naive_Bayes_IRIS_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Baixando os dados IRIS da biblioteca sklearn Python

O conjunto de dados flor Iris de Fisher é um conjunto de dados multivariados introduzido pelo estatístico e biólogo britânico Ronald Fisher em seu artigo de 1936 como um exemplo de análise discriminante linear. 

O conjunto de dados consiste em 50 amostras de cada uma das três espécies de Iris ( Iris setosa, Iris virginica e Iris versicolor). Quatro variáveis foram medidas em cada amostra: o comprimento e a largura das sépalas e pétalas, em centímetros. Com base na combinação dessas quatro características, Fisher desenvolveu um modelo discriminante linear para distinguir as espécies umas das outras.

Leia mais em: https://pt.wikipedia.org/wiki/Conjunto_de_dados_flor_Iris

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Lendo a base de dados. Primeiro baixe o arquivo iris.csv, depois cole o caminho aqui: dados = pd.read_csv('caminho', delimiter=',')

In [57]:
df = pd.read_csv('/content/iris.csv', delimiter=',')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [13]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

definindo as variáveis

In [58]:
x = df.drop(["variety"], axis = 1)
y = df.variety

In [59]:
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

Normalizar variáveis

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler(feature_range = (0, 1))
rescaledx = scaler.fit_transform(x)

In [30]:
rescaledx

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

Antes de rodar precisamos codificar todas as variáveis, observe que a variavel y é qualitativa, precisamos transformar ela em número.

In [43]:
from sklearn import preprocessing

In [44]:
label_encoder = preprocessing.LabelEncoder()

In [60]:
encodery = label_encoder.fit_transform(y)

In [62]:
encodery

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [52]:
rescaledx

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

Baixando o algoritmo Naive Bayes. Vamos utilizar o GaussianNB pois as variáveis sáo normais. Caso contrário poderiamos utilizar outro.

In [55]:
from sklearn.naive_bayes import GaussianNB

GaussianNB()

In [82]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(rescaledx, y, test_size=0.3, random_state=42)


In [83]:
from sklearn.naive_bayes import GaussianNB
naive_iris = GaussianNB()
naive_iris.fit(rescaledx, y)

GaussianNB()

In [84]:
y_pred = naive_iris.predict(x_test)
y_pred

array(['Versicolor', 'Setosa', 'Virginica', 'Versicolor', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Versicolor',
       'Virginica', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Virginica', 'Virginica',
       'Virginica', 'Virginica', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Versicolor', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Versicolor', 'Setosa', 'Setosa'], dtype='<U10')

In [85]:
y_test

73     Versicolor
18         Setosa
118     Virginica
78     Versicolor
76     Versicolor
31         Setosa
64     Versicolor
141     Virginica
68     Versicolor
82     Versicolor
110     Virginica
12         Setosa
36         Setosa
9          Setosa
19         Setosa
56     Versicolor
104     Virginica
69     Versicolor
55     Versicolor
132     Virginica
29         Setosa
127     Virginica
26         Setosa
128     Virginica
131     Virginica
145     Virginica
108     Virginica
143     Virginica
45         Setosa
30         Setosa
22         Setosa
15         Setosa
65     Versicolor
11         Setosa
42         Setosa
146     Virginica
51     Versicolor
27         Setosa
4          Setosa
32         Setosa
142     Virginica
85     Versicolor
86     Versicolor
16         Setosa
10         Setosa
Name: variety, dtype: object

In [86]:
import sklearn.metrics
lbs = ['Versicolor', 'Setosa', 'Virginica']
print(sklearn.metrics.confusion_matrix(y_test, y_pred, labels = lbs))

[[13  0  0]
 [ 0 19  0]
 [ 0  0 13]]


In [88]:
print(sklearn.metrics.accuracy_score(y_test, y_pred))

1.0


In [89]:
print(sklearn.metrics.precision_score(y_test, y_pred, labels = lbs, pos_label=1,average='micro'))

1.0


In [90]:
print(sklearn.metrics.recall_score(y_test, y_pred, labels = lbs, pos_label=1,average='micro'))

1.0


In [91]:
print(sklearn.metrics.f1_score(y_test, y_pred, labels = lbs, pos_label=1,average='micro'))

1.0
